sudo: required

language: php
php:
  - '5.6'

install:
  - cd ./backend
  - composer install

before_script:
  - which php
  - sudo /usr/bin/env php -S 127.0.0.1:80 -t ./www/ &

script:
  - ./vendor/bin/phpunit

addons:
  hosts:
    - acmepay.local
